### ISSUE TITLE
Decoding audio data: RFCOMM channel 1 has no traffic when connected to PC?

### ISSUE THREAD

**Issue by spohtl** [khusmann/benlink#2]
Hi, I love the work you're doing on these radios! I tried taking a shot at decoding the audio traffic, and I think I have the encoding figured out. These lines in the disassembled app code were particularly informative:
![Screenshot_20241229_184807](https://github.com/user-attachments/assets/191302c5-a196-433b-b7f0-32be992033f0)
![Screenshot_20241229_184724](https://github.com/user-attachments/assets/7f13d86e-3082-48a3-a6a7-8c18d846117d)
![Screenshot_20241229_184709](https://github.com/user-attachments/assets/96797a0c-512a-45cf-bb9c-592b102ade7d)

Basically, the audio data sent over RFCOMM is SBC encoded frames, and the SBC config is as follows:
```
blockSize = 16
subBands = 8
sampleRate = 32000
bitPool = 18
mode = SBC_MODE_MONO;
```
There is a 2 byte header before the SBC frame begins, which takes the form of `0x7f 0x00` where the second byte is the "frame type". `0x00` seems to be an audio frame, `0x01` seems to indicate an end of audio transmission, and `0x02` is sent as an ACK, I think? Either way, I'm pretty sure the audio packet has the following form:
```
    7e         00      9c 71 12 a2   [301 - 307 bytes]      7e
start byte | command | SBC header | ---- SBC data ---- | stop byte
```

Based on that info, I tried making a simple decoder using [libsbc](https://github.com/google/libsbc) that would read data from RFCOMM channel 1 and write it to `.wav` files, similar to how the app generates `.opus` files. However, I cannot get the radio to send any audio data when I connect to it with my Linux pc. I can read and issue commands via BLE and via RFCOMM channel 3 no problem, but channel 1 is completely silent. I tried your `simple_connect` scripts, and `rfcomm bind`, and neither of those can read anything. Have you experienced anything like this? Any ideas what could be going on and what I can try? Is there some command I have to issue first before the radio starts sending audio?
Thanks!

**Comment by khusmann** [comment]
Hey, welcome to the project and fantastic work!

What radio do you have? And what is the output of `sdptool records <device uuid>`? 

Audio was on channel 1 for my GA-5WB (what I was using when I wrote `simple_connect`). But for my new UV-Pro, it's on channel 2.

Here's the entry from `sdptool records` so you know what to look for:

```
Service Name: BS AOC
Service RecHandle: 0x10001
Service Class ID List:
  UUID 128: 39144315-32fa-40db-85ed-fbfeba2d86e6
Protocol Descriptor List:
  "L2CAP" (0x0100)
  "RFCOMM" (0x0003)
    Channel: 2
Language Base Attr List:
  code_ISO639: 0x656e
  encoding:    0x6a
  base_offset: 0x100
```

**Comment by spohtl** [comment]
Hi, thanks so much for the reply! Yes, I have the UV-Pro, so the audio data was hanging out on channel 2 :) I'll submit a PR with my experiments soon.
